### ISSUE TITLE
[Mac OSX]: compile vertex shader: "ERROR: 0:1: '' :  version '300' is not supported

### ISSUE THREAD

**Issue by ddvlamin** [barnex/scathanna-3d#1]
Config file: config.json
initializing OpenGL...
connecting to REDACTED
connection accepted, joining...
accepted as 1
thread 'main' panicked at 'compile vertex shader: "ERROR: 0:1: '' :  version '300' is not supported\nERROR: 0:1: '' : syntax error: #version\nERROR: 0:2: '' :  #version required and missing.\nERROR: 0:3: '0' : syntax error: integers in layouts require GLSL 140 or later\n"', libs/gl_obj/src/shader.rs:25:63
stack backtrace:
   0:        0x10b661d11 - std::backtrace_rs::backtrace::libunwind::trace::h310ac7aacd577bf8
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x10b661d11 - std::backtrace_rs::backtrace::trace_unsynchronized::had33a05577c9d011
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10b661d11 - std::sys_common::backtrace::_print_fmt::hd9acce3818e5f1bc
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10b661d11 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4edbddd26fc45697
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x10b67d88b - core::fmt::write::h266c957f12b1655a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
   5:        0x10b65c72a - std::io::Write::write_fmt::h65d4ee621e8d810d
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
   6:        0x10b663535 - std::sys_common::backtrace::_print::h9a5ef67cfa8b031e
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10b663535 - std::sys_common::backtrace::print::h99dfbbc518768f3b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10b663535 - std::panicking::default_hook::{{closure}}::h5b4886cd9f93dfca
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
   9:        0x10b66311f - std::panicking::default_hook::h986d152c7bd7e732
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
  10:        0x10b663c20 - std::panicking::rust_panic_with_hook::h151f3b3bf37b4f17
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:624:17
  11:        0x10b6636be - std::panicking::begin_panic_handler::{{closure}}::hf6660086d9ebd48c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
  12:        0x10b662187 - std::sys_common::backtrace::__rust_end_short_backtrace::h34152178ea368a9a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  13:        0x10b66362a - rust_begin_unwind
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  14:        0x10b6950bf - core::panicking::panic_fmt::hb64a2db862b4aca0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
  15:        0x10b6951a5 - core::result::unwrap_failed::hd3218c9fc9801751
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
  16:        0x10b4ed716 - gl_obj::shader::Shader::new_vertex::h8e6387ebfa847815
  17:        0x10b47d608 - scathanna_core::engine::shaders::shaders::Shaders::new::h4941b5a0fe635aa1
  18:        0x10b4e77a7 - scathanna_core::engine::engine::Engine::new::had1f7ed92154d18b
  19:        0x10b47e328 - scathanna_core::game::gl_client::gl_client::GLClient::new::h94c445f6783fe6a6
  20:        0x10b4dc76c - scathanna_core::game::net::client::net_client::NetClient::connect::he47e121b82cf90a0
  21:        0x10b445bb1 - scathanna::main::h17052c339defb0e2
  22:        0x10b451fb6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9c559a05b1e4edea
  23:        0x10b45200c - std::rt::lang_start::{{closure}}::h04bc0ea84f632bcf
  24:        0x10b6619ff - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h042bcf1eeb382749
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:259:13
  25:        0x10b6619ff - std::panicking::try::do_call::h58aa98b024209748
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  26:        0x10b6619ff - std::panicking::try::hcfc7bc2af44bc609
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  27:        0x10b6619ff - std::panic::catch_unwind::h88980c0eb694c110
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  28:        0x10b6619ff - std::rt::lang_start_internal::{{closure}}::hc07a850a9bc371e5
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128:48
  29:        0x10b6619ff - std::panicking::try::do_call::h061d0434866b3d81
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  30:        0x10b6619ff - std::panicking::try::h8d38c4e20b01fbf0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  31:        0x10b6619ff - std::panic::catch_unwind::hc41b36baa54eb12d
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  32:        0x10b6619ff - std::rt::lang_start_internal::h59ad95b3bebc83b2
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128:20
  33:        0x10b446619 - _main

**Comment by barnex** [comment]
Looks like your graphics driver does not support OpenGL ES 3.0.0.

**Comment by barnex** [comment]
In dab230607158c4c01de3e7de9a5438d732573e31 I have moved to GL 4.1, which I believe should be supported on MacOSX.
